### ISSUE TITLE
Option for preview

### ISSUE THREAD

**Issue by etrnal70** [crispgm/telescope-heading.nvim#1]
Hey, thanks for the extension ! Can you add option to show preview of the content of the headings ?

**Comment by crispgm** [comment]
This is a good idea. I'd like to add this feature but now I have no idea about how the previews work because of lacking of documentation and demo from telescope. I will investigate this later if I can find a possible approach.

**Comment by crispgm** [comment]
@etrnal70 just figured out this, please try the new version :)

**Comment by etrnal70** [comment]
Thank you, it works great !
