### ISSUE TITLE
Use TreeSitter to parse document for headings

### ISSUE THREAD

**Issue by maxRN** [crispgm/telescope-heading.nvim#15]
Are there any plans to use https://github.com/nvim-treesitter/nvim-treesitter for parsing documents and finding headings? I think it would be a cool improvement and this could open up the possibility for more features later on, such as finding code blocks, lists, etc.

I'm talking mostly about Markdown here.

**Comment by crispgm** [comment]
The idea is great. Actually this is my initial plan but I personally did not find sufficient docs or demos for that.

**Comment by maxRN** [comment]
I'm also really new to TreeSitter but I'm glad to hear your are open to the idea 😃 

I've found the [official Neovim TreeSitter playground](https://github.com/nvim-treesitter/playground) repository very helpful. (It says you need nightly Neovim, but I only have 0.6 and it works fine for me so far.)
After installing the plugin you can run `:TSPlaygroundToggle` to show the *abstract syntax tree* (AST) in a side view.
I've attached a screenshot of what the AST looks like for an example MarkDown document.

When you hover over the nodes in the tree, the corresponding part of the document is highlighted.
<img width="1440" alt="Screenshot 2022-02-27 at 08 50 15" src="https://user-images.githubusercontent.com/56630671/155873556-2617db6a-4b9c-49c6-851b-ccfe5417d5cb.png">

As to queries, when you hit `o` while you are in the AST view, you open a third window in which you can edit your own queries. A very basic one I've tried is `(atx_heading) @capture` which highlights *all* headings (h1, h2, etc.) in the document. Note: To highlight them in the document you have to move your cursor on the the `@capture` part of the query.
<img width="1440" alt="Screenshot 2022-02-27 at 08 58 03" src="https://user-images.githubusercontent.com/56630671/155873853-24cf643f-ce91-4459-b8fc-0e14aef61e61.png">

Other plugins that I know of that use TreeSitter are this [refactoring](https://github.com/ThePrimeagen/refactoring.nvim) plugin, and this [tabout](https://github.com/abecodes/tabout.nvim) one. So I guess we could look there for some inspiration.

**Comment by crispgm** [comment]
@maxRN https://www.reddit.com/r/neovim/comments/kx1ceh/need_a_little_help_with_tree_sitter_query_matching/ I found this guide, which is basically the scenario we need. I would dive into this recently.

And now, tree-sitter only supports markdown and rst, not capable for every format. This is a cons.

**Comment by crispgm** [comment]
```lua
local function ts_get_headings(filepath)
    local headings = {}
    local query = [[
    (atx_heading) @heading
    ]]
    local parsed_query = ts.parse_query('markdown', query)
    local bufnr = vim.api.nvim_get_current_buf() or 0
    local parser = ts.get_parser(bufnr, 'markdown')
    local root = parser:parse()[1]:root()
    local start_row, _, end_row, _ = root:range()

    for _id, node in parsed_query:iter_captures(root, bufnr, start_row, end_row) do
        local row, _ = node:range()
        local line = vim.fn.getline(row + 1)
        table.insert(headings, {
            heading = vim.trim(line),
            line = row,
            path = filepath,
        })
    end
    return headings
end
```

I think this works good. All I have to finish this feature is to add an option to use tree sitter and some checks.

**Comment by crispgm** [comment]
@maxRN Treesitter parsing for markdown is merged. You may try it. Thanks for your idea.
