### ISSUE TITLE
Vim help headings don’t show

### ISSUE THREAD

**Issue by comfortablynick** [crispgm/telescope-heading.nvim#20]
The headings work fine for me in Markdown documents but not in help files

**Comment by crispgm** [comment]
@comfortablynick Thanks for reporting. It seems that the syntax tree of vim-help is changed.

**Comment by crispgm** [comment]
@comfortablynick I think it's fixed. Please try with the latest commit. :)

**Comment by comfortablynick** [comment]
@crispgm Thanks, works great now.
