### ISSUE TITLE
Help treesitter parser has changed

### ISSUE THREAD

**Issue by fbearoff** [crispgm/telescope-heading.nvim#23]
I am getting the following error if I invoke `:Telescope heading` in a vim help file:

> No treesitter language parser installed for [help]. Fallback to normal parser.

My guess is this is related to the change of the treesitter parser for help files to "vimdoc" https://github.com/neovim/tree-sitter-vimdoc/commit/b2ec4ec5f7be24cb6f7ccffafd7204477fe5784a

**Comment by crispgm** [comment]
> I am getting the following error if I invoke `:Telescope heading` in a vim help file:
> 
> > No treesitter language parser installed for [help]. Fallback to normal parser.
> 
> My guess is this is related to the change of the treesitter parser for help files to "vimdoc" [neovim/tree-sitter-vimdoc@b2ec4ec](https://github.com/neovim/tree-sitter-vimdoc/commit/b2ec4ec5f7be24cb6f7ccffafd7204477fe5784a)

Would you mind confirming it's `TSInstall`ed?

**Comment by fbearoff** [comment]
Confirmed, I have the `vimdoc` parser installed. If you look in the output from `TSInstallInfo` there is no entry for `help` anymore.

**Comment by crispgm** [comment]
> 

It's like changing name to `vimdoc` would work. Would you mind testing it?

**Comment by fbearoff** [comment]
Happy to, point me to a commit for testing

**Comment by crispgm** [comment]
@fbearoff Hello, I think I have figured it out.
You may try this PR: https://github.com/crispgm/telescope-heading.nvim/pull/24
