### ISSUE TITLE
Is there a way to not sort the headings?

### ISSUE THREAD

**Issue by angelidis** [crispgm/telescope-heading.nvim#25]
hello,

what an awesome plugin!

Is there a way to **not** sort the headings in the picker?

this would be very convenient for markdown files, where the headings have a logical order.

for example:
```
# heading 1
## sub1
## sub2
# heading 2
## a title
## another title
```

The plugin works perfectly as is, just wondering if I've missed something.

**Comment by crispgm** [comment]
IMO, telescope extensions are either pickers or sorters. telescope-heading is picker and sorted by file sorter (otherwise, generic sorter). I may control the default order, now it's the same as its position, the most natural way. You may also customize the default sorter by yourself but it change only the order when you are inputting.

**Comment by pmatulis** [comment]
I'm hitting the same problem. My Markdown headers are shown in reverse order, which is non-intuitive.

**Comment by crispgm** [comment]
> I'm hitting the same problem. My Markdown headers are shown in reverse order, which is non-intuitive.

Would you mind showing your triage information? I think the implementation is in order not reverse order.

**Comment by pmatulis** [comment]
Yeah I think I need to change the sorting strategy to flip things around.

![image](https://github.com/crispgm/telescope-heading.nvim/assets/6303808/6f8e17b5-066e-4464-a85c-7fddfc7e6bdc)

**Comment by crispgm** [comment]
> Yeah I think I need to change the sorting strategy to flip things around.
> 
> ![image](https://user-images.githubusercontent.com/6303808/271121309-6f8e17b5-066e-4464-a85c-7fddfc7e6bdc.png)

It looks that the result is correct, in which `HEADING ONE` is the first approachable. You can change the layout/UI of your telescope.nvim to make it look in order.

IMO, telescope.nvim does not provide ordering mechanism but we can define option to enable different sorting method.

**Comment by crispgm** [comment]
telescope-heading lists in order, as you expected. The behavior of your screenshot is because the default theme of telescope, which shows everything reversely. If you setup `ivy` theme like my screenshot on README, it would be in order. cc @angelidis

**Comment by sankantsu** [comment]
This issue is already closed, but I will comment about my current setting.
I think following setting is what @angelidis, @pmatulis want.
Hope this helps!

```lua
require("telescope").setup({
  extensions = {
    heading = {
      picker_opts = {
        sorting_strategy = "ascending", -- "descending" by default
      },
    },
  }
})
```
