### ISSUE TITLE
Possibility to support LaTeX tex files

### ISSUE THREAD

**Issue by dericktseng** [crispgm/telescope-heading.nvim#8]
Is it possible to implement searching through sections for tex files?

**Comment by crispgm** [comment]
@MetriC-DT yes, but is there any docs about that? I am not a tex user so that I can investigate that later.

**Comment by dericktseng** [comment]
I couldn't find any official documentation, but from personal experience and [overleaf](https://www.overleaf.com/learn/latex/Sections_and_chapters) the "headings" in latex usually consists of one of the following:
```latex
\part{Part Title}
\chapter{Chapter Title}
\section{Section Name}
\subsection{Subsection Name}
\subsubsection{Subsubsection Name}
\paragraph{paragraph}
\subparagraph{subparagraph}

\part*{Part Title}
\chapter*{Chapter Title}
\section*{Section Name}
\subsection*{Subsection Name}
\subsubsection*{Subsubsection Name}
\paragraph*{paragraph}
\subparagraph*{subparagraph}
```

**Comment by dericktseng** [comment]
These are the segments to ignore:
Comments and math segments in tex are of the format:
```latex
% this is a comment %
$This is an inline math block$
$$This is also a math block$$
\$ This is NOT a math block \$
\[
This is also a math block
\]
```
Though I believe that putting a `\section` string or any other heading keyword within a math block is a pathological edge case and is probably never seen.
